server:
 port: 8084
spring:
  application:
    name: USERS
  #database confighanu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/microservice?&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
  
  #hibernate config
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "optional:configserver:http://localhost:8093"

# circuitbreakers config
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 

  endpoint:
    health:
      show-details: always
      
# resilience4j config for circuitbreakers config
resilience4j:
  circuitbreaker:
    instances:
      # config for ratingBreaker
      ratingBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
  
  # this is for retry config
  retry:
    instances:
      ratingService:
        max-attempts: 3
        wait-duration: 5s
            
#logging
logging:
  level:
    root: INFO
  file:
    name: /home/vinit/Desktop/logs/api.log
    
