server:
  port: 8091
  
spring:
  application:
    name: APIGATEWAY
    
#cloud config for api gateway    
  cloud:
    gateway:
      routes:
      - id: USERS
        uri: lb://USERS
        predicates:
        - Path=/users/**
        
      - id: HOTELS
        uri: lb://HOTELS
        predicates:
        - Path=/hotels/**
        
      - id: RATINGS
        uri: lb://RATINGS
        predicates:
        - Path=/ratings/**
        
#eureka clint config
  config:
    import: "optional:configserver:http://localhost:8093"